- project:
    templates:
      - openstack-python-jobs-no-constraints
      - openstack-python35-jobs-no-constraints
    check:
      jobs:
        - dib-nodepool-functional-openstack-gentoo-src:
            voting: false
        - dib-nodepool-functional-openstack-centos-7-src
        - dib-nodepool-functional-openstack-fedora-29-src
        - dib-nodepool-functional-openstack-ubuntu-trusty-src
        - dib-nodepool-functional-openstack-ubuntu-xenial-src
        - dib-nodepool-functional-openstack-ubuntu-bionic-src
        - dib-nodepool-functional-openstack-opensuse-150-src
        - dib-nodepool-functional-openstack-opensuse-tumbleweed-src
    gate:
      jobs:
        - dib-nodepool-functional-openstack-centos-7-src
        - dib-nodepool-functional-openstack-fedora-29-src
        - dib-nodepool-functional-openstack-ubuntu-trusty-src
        - dib-nodepool-functional-openstack-ubuntu-xenial-src
        - dib-nodepool-functional-openstack-ubuntu-bionic-src
        - dib-nodepool-functional-openstack-opensuse-150-src
        - dib-nodepool-functional-openstack-opensuse-tumbleweed-src
    experimental:
      jobs:
        - dib-nodepool-functional-openstack-debian-stretch-src
        - dib-nodepool-functional-openstack-debian-buster-src
