- project:
    templates:
      - openstack-python-jobs-no-constraints
      - openstack-python35-jobs-no-constraints
      - openstack-python36-jobs-no-constraints
    check:
      jobs:
        - opendev-buildset-registry
        - nodepool-build-image-siblings
        - dib-nodepool-functional-openstack-gentoo-src:
            voting: false
        - dib-nodepool-functional-openstack-centos-7-src
        - dib-nodepool-functional-openstack-centos-8-stream-src
        - dib-nodepool-functional-openstack-centos-9-stream-src
        - dib-nodepool-functional-openstack-ubuntu-xenial-src
        - dib-nodepool-functional-openstack-ubuntu-bionic-src
        - dib-nodepool-functional-openstack-ubuntu-focal-src
        - dib-nodepool-functional-openstack-debian-bullseye-src
        - dib-nodepool-functional-openstack-rockylinux-8-containerfile-src
    gate:
      jobs:
        - opendev-buildset-registry
        - nodepool-build-image-siblings
        - dib-nodepool-functional-openstack-centos-7-src
        - dib-nodepool-functional-openstack-centos-8-stream-src
        - dib-nodepool-functional-openstack-centos-9-stream-src
        - dib-nodepool-functional-openstack-ubuntu-xenial-src
        - dib-nodepool-functional-openstack-ubuntu-bionic-src
        - dib-nodepool-functional-openstack-ubuntu-focal-src
        - dib-nodepool-functional-openstack-debian-bullseye-src
        - dib-nodepool-functional-openstack-rockylinux-8-containerfile-src
    experimental:
      jobs:
        - opendev-buildset-registry
        - nodepool-build-image-siblings
        - dib-nodepool-functional-openstack-opensuse-15-src
        - dib-nodepool-functional-openstack-opensuse-tumbleweed-src
